HuaweiBigData/carbondata

- integration/spark/src/main/java/org/carbondata/integration/spark/load/CarbonLoaderUtil.java
- integration/spark/src/main/scala/org/carbondata/integration/spark/rdd/CarbonQueryRDD.scala
- integration/spark/src/test/java/org/carbondata/integration/spark/load/CarbonLoaderUtilTest.java
Based on number of executor.cores per node, distribute blocks to each task. So that query load is evenly distributed to all tasks.
> [BUG] Distribute Query blocks to nodes, to balance load to tasks

- core/src/main/java/org/carbondata/core/datastorage/store/impl/FileHolderImpl.java
1 The filePath parameter of updateCache method is  absolute path, So I think we don't need to use CarbonFile.getAbsolutePath()
2 During data loading, we invoke the updateCache method frequently, maybe reach a million times. So we should not new a instance of CarbonFile in the updataCache method.
link [Issue-324](https://github.com/HuaweiBigData/carbondata/issues/324)
> [Issue-324]Data loading performance optimization: optimize FileHolderImpl

- core/src/main/java/org/carbondata/core/util/CarbonMetadataUtil.java
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeDirectDictionaryTestCase.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeDirectDictionaryWithNoDictTestCase.scala
- processing/src/main/java/org/carbondata/processing/dimension/load/command/impl/CSVDimensionLoadCommand.java
- processing/src/main/java/org/carbondata/processing/graphgenerator/GraphGenerator.java
- processing/src/main/java/org/carbondata/processing/graphgenerator/configuration/GraphConfigurationInfo.java
- processing/src/main/java/org/carbondata/processing/schema/metadata/ColumnSchemaDetails.java
- processing/src/main/java/org/carbondata/processing/schema/metadata/ColumnSchemaDetailsWrapper.java
- processing/src/main/java/org/carbondata/processing/schema/metadata/ColumnsInfo.java
- processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenMeta.java
- processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
- processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/FileStoreSurrogateKeyGenForCSV.java
- processing/src/main/java/org/carbondata/processing/util/CarbonSchemaParser.java
1. Direct dictionary dataload failure when used with No dictionary columns
2. Clean up is not happening after the TestTimestampDataTypeDirectDictionary execution
3. Fixed Import issue of CarbonMetadataUtil
4. Rename TimestampDataTypeDirectDictionary_FT to TestTimestampDataTypeDirectDictionary
> [Issue- 479] Direct dictionary dataload failure when used with No dictionary columns

- core/src/main/java/org/carbondata/core/util/ByteUtil.java
The PR https://github.com/HuaweiBigData/carbondata/pull/396 test case finds the below error 
`java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeHi(TimSort.java:899)
at java.util.TimSort.mergeAt(TimSort.java:516)
at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
at java.util.TimSort.sort(TimSort.java:254)
at java.util.Arrays.sort(Arrays.java:1438)
at org.carbondata.processing.sortandgroupby.sortdata.SortDataRows$1.call(SortDataRows.java:367)`
Here the comparison is going wrong, because it supposed to be unsafe comparison but here mixed both.
This scenario is covered by the testcases of PR https://github.com/HuaweiBigData/carbondata/pull/396
> [Part of PR 396]Fixed error " Comparison method violates its general contract" .

- integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
#531 , modification
Assigning at least 1 task per node, instead of zero.
> [Issue - 531] The error of '/ by zero' will random occurs when query from the table

- core/src/main/java/org/carbondata/core/carbon/metadata/schema/table/column/ColumnSchema.java
- format/src/main/thrift/schema.thrift
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceRelation.scala
- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithNoMeasure.scala
- processing/src/main/java/org/carbondata/processing/csvload/GraphExecutionUtil.java
Loading data with measure column was failing, to fix the same added added the dummy measure when no measure is defined the create table DDL.
Select * from TableName;
Output
Must be merged after PR  #425
> [Issue- 408] Data Load is failing when no measure is used in create cube command

- core/pom.xml
- core/src/main/java/org/carbondata/core/locks/ZooKeeperLocking.java
- core/src/test/java/org/carbondata/core/locks/ZooKeeperLockingTest.java
There are three issues with that ZooKeeper test case
1. Some times test case hangs while starting the zookeeper server, that is the bug in zookeeper 3.4.8, it could be solved by either downgrading to 3.4.7 or overriding the ZooKeeperServer start method. Please have a look at https://issues.apache.org/jira/browse/ZOOKEEPER-2383
2. It generates very big log files under core/version-2 folder. It could be solved by moving the folder to target.
3. Test case some times failing because it cannot get the node, It is because the baseNode existance and creation is added to Watcher. It calls every time for each call. Calls some times hangs there. So we can pre-create the base node solves the issue.
> [Issue 560] Zookeeper test case fails randomly and generates big log files under core package

- integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceRelation.scala
When table is dropped and user runs below command
"drop table if exists <tablename>"
carbon is giving issue while evaluating size as directory doesn't exist.
Fixe is made to check if directory exists than only evaluate size.
> [Bug 610]carbondatasourcerelation size issue fix

- integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
- integration/spark/src/main/scala/org/carbondata/spark/util/CommonUtil.scala
- integration/spark/src/test/scala/org/apache/spark/sql/TestCarbonSqlParser.scala
1.Measure should not be part of column group
2.No dictionary column should not be part of column group
3.same columname should not be specified two different column group
4.complex dimension should not be part of column group
6.timestamp should not be part of column group
7.Added test cases
> [Issue 607]Validation for column group

- core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
- core/src/main/java/org/carbondata/core/locks/HdfsFileLock.java
- core/src/main/java/org/carbondata/core/locks/LocalFileLock.java
- core/src/main/java/org/carbondata/core/locks/LockUsage.java
- core/src/main/java/org/carbondata/core/locks/ZooKeeperLocking.java
- core/src/main/java/org/carbondata/core/util/CarbonProperties.java
- integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
- integration/spark/src/main/scala/org/carbondata/spark/rdd/Compactor.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionNoDictionaryTest.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionTest.scala
1. changed the property carbon.enable.load.merge to  "carbon.enable.auto.load.merge". this will enable/disable the compaction done during the data load. i.e minor compaction.
2. running compaction in separate thread.
3. DEFAULT_ENABLE_COMPACTION_BASED_ON_DATE = "false"
4. changed the minor compaction behaviour. minor compaction will happen only when the configured size is reached. not before that.
> [Issue-578] Threaded compaction

- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
when dfs.blocksize of hadoop configuration set human readable format as 64k/128M/256G. etc, will throw exception when load data, since hadoop.Configuration#getLong() couldn't revert it to long rather than hadoop.Configuration#getLongBytes().
> [Bug] Fix bug when hadoop configueration item dfs.blocksize config human readable format

- core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
- core/src/main/java/org/carbondata/core/util/DataTypeUtil.java
- integration/spark/src/test/resources/data2.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/HighCardinalityDataTypesTestCase.scala
- processing/src/main/java/org/carbondata/processing/graphgenerator/GraphGenerator.java
- processing/src/main/java/org/carbondata/processing/graphgenerator/configuration/GraphConfigurationInfo.java
- processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenMeta.java
- processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
- processing/src/main/java/org/carbondata/processing/util/CarbonSchemaParser.java
- processing/src/main/java/org/carbondata/processing/util/RemoveDictionaryUtil.java
Problem:
NOT NULL should not display any null values in the output
No_Dictionary columns wont support double/decimal type, but in case of integer type data this scenario has to be handled.
issue is happening since no dictionary integer type column block contain String value, so when filter comparison happens the actual data which is a non null value  present in block
will be compared with default null member and the null will not get filtered out.
Solution:
To solve this issue while performing data load the no dictionary integer/other type of column excluding String type contains any un parseable data
the system has to convert it to default null member value.
> [Bug] NOT NULL should not display any null values in the output

- core/src/main/java/org/carbondata/core/cache/dictionary/ColumnDictionaryInfo.java
- core/src/main/java/org/carbondata/core/writer/sortindex/CarbonDictionarySortModel.java
- core/src/main/java/org/carbondata/query/expression/LiteralExpression.java
- core/src/main/java/org/carbondata/query/filter/resolver/ConditionalFilterResolverImpl.java
- core/src/main/java/org/carbondata/query/filters/measurefilter/util/FilterUtil.java
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala
SortModel reference was not sorting the forward dictionary values when null member/nonparseable was present in the column data other than string.
In filter layer also when IS NOT NULL filter resolve happens the filter expression has to be evaluated with all the filter values when the column data has both null and unparseable data in different data type column other than String.
> [Bug] Sort index not created properly for null members in case of String type

- integration-testcases/src/test/scala/org/apache/spark/sql/common/util/CarbonHiveContext.scala
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonCatalystOperators.scala
- integration/spark/src/test/scala/org/apache/spark/sql/common/util/CarbonHiveContext.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/aggquery/AllDataTypesTestCaseAggregate.scala
Following queries was not working 
select SID,length( MSISDN),max(LAYER1ID),min(LAYER1ID),avg(LAYER1ID) from smart_500 group by SID,length( MSISDN) order by SID limit 10;
select age,trim(imei),avg(gamepointid),avg(age) from table03 group by age,trim(imei);
It is because we are converting to carbon aggregates in `CarbonCatalystOperators` but going to detail query in `carbonOperators`, so it causes unexpected results. This PR add validation to made it sync between two classes
> Fixed bug  select function like trim or length along with avg aggregator

- integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionNoDictionaryTest.scala
After compaction segment id will be decimal value, so delete segment by id query should support decimal value also as id
> [Issue-578] Compaction Support : Delete segment by id query should support decimal value also as id

- assembly/pom.xml
It seems spark1.6 URL classloader server is buggy, it returns `META-INF/vfs-providers.xml` two times from jar file even though it is only one file. Because of this reason commons-vfs is failing. Any way we don't required this xml file to read as we are already handling in code.
So I am excluding it in assembly file. It works fine now both in Spark 1.5 and 1.6.
> Fixed data loading failure in Spark1.6 spark shell

- integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/createtable/TestCreateTableSyntax.scala
when we create table, set double or decimal dataType column as  DICTIONARY_EXCLUDE
`create table carbontable(id int, name string, dept string, mobile array<string>, country string, salary double) STORED BY 'org.apache.carbondata.format'`
the system should throw exception, and create table failed
> double or decimal dataType should not be set as DICTIONARY_EXCLUDE

- integration/spark/src/main/scala/org/apache/spark/sql/optimizer/CarbonOptimizer.scala
Query filters which are applied through dataframe are not pushed down to carbon layer. This PR fixes that problem.
> Fixed issue of dataframe query filters are not pushed down

- core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
- core/src/main/java/org/carbondata/query/expression/Expression.java
- core/src/main/java/org/carbondata/query/expression/ExpressionResult.java
- core/src/main/java/org/carbondata/query/expression/arithmetic/AddExpression.java
- core/src/main/java/org/carbondata/query/expression/arithmetic/DivideExpression.java
- core/src/main/java/org/carbondata/query/expression/arithmetic/MultiplyExpression.java
- core/src/main/java/org/carbondata/query/expression/arithmetic/SubstractExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/EqualToExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/GreaterThanEqualToExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/GreaterThanExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/InExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/LessThanEqualToExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/LessThanExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/ListExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/NotEqualsExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/NotInExpression.java
- core/src/main/java/org/carbondata/query/expression/exception/FilterIllegalMemberException.java
- core/src/main/java/org/carbondata/query/expression/logical/AndExpression.java
- core/src/main/java/org/carbondata/query/expression/logical/NotExpression.java
- core/src/main/java/org/carbondata/query/expression/logical/OrExpression.java
- core/src/main/java/org/carbondata/query/filter/executer/RowLevelFilterExecuterImpl.java
- core/src/main/java/org/carbondata/query/filter/resolver/RestructureFilterResolverImpl.java
- core/src/main/java/org/carbondata/query/filter/resolver/RowLevelRangeFilterResolverImpl.java
- core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/CustomTypeDictionaryVisitor.java
- core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/DictionaryColumnVisitor.java
- core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/NoDictionaryTypeVisitor.java
- core/src/main/java/org/carbondata/query/filters/measurefilter/util/FilterUtil.java
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala
Row level scanning filters while filtering invalid member giving exception, as per the hive compatibility
empty rows will be displayed .
Problem:
While performng Row level scanning to apply Multi dimension filters, if any non parseable data present
filter layer was throwing out run time exception.
Solution:
Filter layer shall provide empty resultset in this scenario, if any NumberFormatException happens while comparison, catch the same and pass empty resultset.
> [Bug] Row level scanning filters while filtering invalid member giving exception

- core/src/main/java/org/carbondata/core/locks/LocalFileLock.java
- core/src/main/java/org/carbondata/core/locks/LockUsage.java
- integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
- integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionLockTest.scala
- processing/src/main/java/org/carbondata/lcm/status/SegmentStatusManager.java
If the table status file needs to be updated then the table status lock should be acquired and done.
if the locking is failed because of other process locking then need to fail the complete Process.
If table status lock is failed to acquire then complete data load or the compaction should fail.
Correcting the local lock.
Adding the FT for compaction locking.
> [BUG] Failed to update table status on concurrent compaction and data load.

- processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
The issue was happening due to concurrent access of same file by three executors, if one of executor hold the lease on the file, the other two were not getting the lease, and ending up by throwing 
FileNotFoundException: No lease on filePath. 
Solution:
Adding the taskNo in the path to avoid concurrent access of same file.
> [Issue - CARBONDATA-9] Fixed No lease issue on the bad record log file.

- core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
- core/src/main/java/org/carbondata/core/util/CarbonProperties.java
- integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
1. minor compaction will take the number of segments to be merged instead of size.
2. 2 levels of merging is possible. 1st level will merge the segments which are not merged. 2nd level will merge the 1st level of merged segments.
3. suppose if the user has configured the property "carbon.compaction.level.threshold" as "4,3"  then the first level of threshold is 4 . i.e 4 segments will keep on getting merged.
2nd level threshold is 3. so that 3 segments which are already merged in 1st level will get merged together.
4. default value of the threshold is 4,3 so that 12 segments will get merged together.
5. fixed the bug in the Major compaction segment identification based on size.
> [BUG] Changing the minor compaction behavior to work on segment numbers.

- core/src/main/java/org/carbondata/core/util/CarbonProperties.java
when we config high.cardinality.threshold=10000 in carbon.properties, it doesn't work.
in this pr, i have fixed this issue
> Dictionary creation is successful when distinct count of this column above high.cardinality.threshold 

- core/src/main/java/org/carbondata/core/keygenerator/directdictionary/DirectDictionaryGenerator.java
- core/src/main/java/org/carbondata/core/keygenerator/directdictionary/timestamp/TimeStampDirectDictionaryGenerator.java
- core/src/main/java/org/carbondata/query/expression/ExpressionResult.java
- core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/CustomTypeDictionaryVisitor.java
- integration/spark/src/test/resources/data2_DiffTimeFormat.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala
Timestamp with different format compare to spark date format will fail to provide filter result. this is because while querying the engine is trying to get the direct surrogate based in user defined time format in properties file.
> [Bug] Timestamp with different format compare to spark date format is failing while query

- hadoop/src/test/java/org/carbondata/hadoop/test/util/StoreCreator.java
- integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoadModel.java
- integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
- integration/spark/src/test/resources/datawithescapecharacter.csv
- integration/spark/src/test/resources/datawithspecialcharacter.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithHiveSyntax.scala
- processing/src/main/java/org/carbondata/processing/api/dataloader/DataLoadModel.java
- processing/src/main/java/org/carbondata/processing/csvload/DataGraphExecuter.java
- processing/src/main/java/org/carbondata/processing/csvreaderstep/BlockDataHandler.java
- processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInput.java
- processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInputData.java
- processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInputMeta.java
- processing/src/main/java/org/carbondata/processing/dataprocessor/DataProcessTaskStatus.java
- processing/src/main/java/org/carbondata/processing/dataprocessor/IDataProcessStatus.java
- processing/src/main/java/org/carbondata/processing/graphgenerator/GraphGenerator.java
in currectly flow,escape character will no skip in kettle,while dictionary generation will skip the escape character .and if the value no start with quote,it will no skip also.
like "ab\c"->"abc",a"b\c"->a"b\c"
also,this pr fix the value like ab"c"d,which contain double quote in middle of value.
as suggesoin,we need to make the same parser in phase 1:global dictionary and phase 2:data loading.
using same parser:univocity parser. then all defects about different parser will no comes any more.
> [Bug]skip escape char in kettle and fix quote in middle of value

- core/src/main/java/org/carbondata/query/carbon/executor/util/QueryUtil.java
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/HighCardinalityDataTypesTestCase.scala
When no measure present in the carbon table we are adding default measure . in case of count (*) with filter query by default we are adding default measure but in this case we first measure is a dummy measure which will not have add data so in that case adding first dimension
> Fixed count star with filter issue

- core/src/main/java/org/carbondata/core/util/CarbonUtil.java
- core/src/main/java/org/carbondata/query/filter/executer/ExcludeFilterExecuterImpl.java
- core/src/main/java/org/carbondata/query/filter/executer/IncludeFilterExecuterImpl.java
- core/src/main/java/org/carbondata/query/filter/executer/RowLevelRangeGrtThanFiterExecuterImpl.java
- core/src/main/java/org/carbondata/query/filter/executer/RowLevelRangeGrtrThanEquaToFilterExecuterImpl.java
- core/src/main/java/org/carbondata/query/filter/executer/RowLevelRangeLessThanEqualFilterExecuterImpl.java
- core/src/main/java/org/carbondata/query/filter/executer/RowLevelRangeLessThanFiterExecuterImpl.java
- core/src/main/java/org/carbondata/query/filter/executer/RowLevelRangeTypeExecuterFacory.java
- core/src/main/java/org/carbondata/query/filter/resolver/AndFilterResolverImpl.java
- core/src/main/java/org/carbondata/query/filter/resolver/ConditionalFilterResolverImpl.java
- core/src/main/java/org/carbondata/query/filter/resolver/FilterResolverIntf.java
- core/src/main/java/org/carbondata/query/filter/resolver/LogicalFilterResolverImpl.java
- core/src/main/java/org/carbondata/query/filter/resolver/RowLevelRangeFilterResolverImpl.java
- core/src/main/java/org/carbondata/query/filters/FilterExpressionProcessor.java
- core/src/main/java/org/carbondata/query/filters/measurefilter/util/FilterUtil.java
- integration/spark/src/test/resources/data2.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/HighCardinalityDataTypesTestCase.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala
Direct surrogate key range filters not able to prune blocks, Now the support is added for direct surrogates column also. previously row level filter evaluation was happening for direct dictionary columns in case of range filters, this will reduce the performance also for such queries which is having timestamp data with range filters applied
Note: The above PR has to be rebased with PR #683 , #683 PR needs to be merged first.
.
> [CARBONDATA-13] Direct surrogate key range filters not able to prune blocks

- integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
level 2 Merge load name is wrongly formed with many precisions.
So forming the merge load name with only one precision.
> [BUG] Merged load name is wrongly formed.

- core/src/main/java/org/carbondata/query/carbon/aggregator/impl/ListBasedResultAggregator.java
- core/src/main/java/org/carbondata/query/carbon/aggregator/impl/MapBasedResultAggregator.java
- core/src/main/java/org/carbondata/query/carbon/executor/impl/AbstractQueryExecutor.java
In case of multiple load and single load or multiple load when  key generator is same then also we were updating the key with the latest segment keygeenerator. problem was when number of records are more then it not required and it will add overhead during query execution for more number of records as bit packing and unpacking is a costly operation.Fixed the same
> Fixed length key updation issue in case of multiple load and single load

- integration/spark/src/main/scala/org/apache/spark/sql/hive/DistributionUtil.scala
- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
Modification:
No need to wait if the existing executors are more than or equal to the required executors.
> [CARBONDATA-57] BLOCK distribution un wanted wait for the executor node even though the sufficient nodes are available

- core/src/main/java/org/carbondata/query/expression/ExpressionResult.java
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/bigdecimal/TestBigDecimal.scala
when query with "select ... from table where decimalFiled=123456.12", the query result is empty, while 123456.12 is in the csv data. and in hive, we can get the correct result.
this is because the code handles double value as new Bigdecimal(double), this is not accurate.
> [CARBONDATA-43][BUG]Handle for decimal filter query "where dicimalFiled=123456.12"

- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonGlobalDictionaryRDD.scala
- integration/spark/src/test/resources/lessthandatacolumndata.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestDataWithDicExcludeAndInclude.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithHiveSyntax.scala
- processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
when csv head is id,name,age,city
if the data record like as the following:
1,a,10,china
2,b
3,c,11,usa
then,when read this row:2,b,generating dicionary will failure,and the remain record (3,c,11,usa)will no generate dictionary.
this pr to prevent put null value to Set,and let it continue.
> [CARBONDATA-36]fix dictionary exception when data column count less then schema

- core/src/main/java/org/carbondata/core/reader/CarbonDictionaryMetadataReaderImpl.java
- core/src/main/java/org/carbondata/core/reader/CarbonDictionaryReaderImpl.java
- core/src/main/java/org/carbondata/core/reader/sortindex/CarbonDictionarySortIndexReaderImpl.java
- core/src/main/java/org/carbondata/core/writer/sortindex/CarbonDictionarySortIndexWriterImpl.java
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
- integration/spark/src/main/scala/org/carbondata/spark/util/CommonUtil.scala
- integration/spark/src/test/scala/org/apache/spark/sql/TestCarbonSqlParser.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/ColumnGroupDataTypesTestCase.scala
1.While defining Column groups, if group is not defined in schema order than data loading is failing
fix is done to arrange the group in schema order
2.Changed Sortindexwriter and SortIndexReader to get pathservice from factory and also changed visibility of cleanupOldSortIndex method to protected
3.Changed DictionaryReader to get pathService from factory and then get carbontable
> [Bug]Arrange ColumnGroups in schema order

- core/src/main/java/org/carbondata/core/carbon/metadata/schema/table/CarbonTable.java
- core/src/main/java/org/carbondata/query/carbon/executor/util/QueryUtil.java
array of array complex column query execution was failing because key size of the primitive column was not proper. This is because while adding the dimension to carbon table complex dimension ordinal was not incremented properly. so complex dimension ordinal for primitive type was not proper and it was pointing to wrong keysize and throwing bufferunderflow execption
> Fixed complex query execution issue.

- core/src/main/java/org/carbondata/core/keygenerator/directdictionary/timestamp/TimeStampDirectDictionaryGenerator.java
- core/src/main/java/org/carbondata/query/expression/DataType.java
- core/src/main/java/org/carbondata/query/expression/ExpressionResult.java
- core/src/main/java/org/carbondata/query/expression/conditional/InExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/NotInExpression.java
- core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/CustomTypeDictionaryVisitor.java
- core/src/main/java/org/carbondata/query/filters/FilterExpressionProcessor.java
- core/src/main/java/org/carbondata/query/filters/measurefilter/util/FilterUtil.java
- integration/spark/src/test/resources/big_int_Decimal.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala
Filter was failing when join condition is been applied between two tables,spark will send optimized logical plan for execution where
timestamp type will change to Long and this since the left expression and right expression was getting different data type issue was happening in case of Timestamp type column filters, For other filter like BigInt and Decimal, expression result was not handling such data type while comparing the expression results.
> [Bug] Filter was failing when join condition

- common/src/main/java/org/carbondata/common/logging/LogService.java
- common/src/main/java/org/carbondata/common/logging/impl/StandardLogService.java
- common/src/main/java/org/carbondata/common/logging/impl/StatisticLevel.java
- core/src/main/java/org/carbondata/core/carbon/querystatistics/QueryStatistic.java
- core/src/main/java/org/carbondata/core/carbon/querystatistics/QueryStatisticsRecorder.java
- core/src/main/java/org/carbondata/query/carbon/executor/impl/AbstractQueryExecutor.java
- core/src/main/java/org/carbondata/query/carbon/executor/impl/QueryExecutorProperties.java
- core/src/main/java/org/carbondata/query/carbon/executor/infos/BlockExecutionInfo.java
- core/src/main/java/org/carbondata/query/carbon/executor/internal/impl/InternalAbstractQueryExecutor.java
- core/src/main/java/org/carbondata/query/carbon/model/QueryModel.java
- core/src/main/java/org/carbondata/query/carbon/result/iterator/AbstractDetailQueryResultIterator.java
- core/src/main/java/org/carbondata/query/carbon/result/iterator/DetailQueryResultIterator.java
- core/src/main/java/org/carbondata/query/carbon/result/preparator/impl/QueryResultPreparatorImpl.java
- hadoop/src/main/java/org/carbondata/hadoop/CarbonInputFormat.java
- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala
added executor side query execution statistics
Message details
Detail Query:
INFO  17-07 03:10:36,236 - [Executor task launch worker-0][partitionID:nest9;queryID:2776118908102_0] Time taken to load the Blocks In Executor for the taskid : 2776118908102_0 Is : 109
INFO  17-07 03:10:36,236 - [Executor task launch worker-0][partitionID:nest9;queryID:2776118908102_0] Time taken to load the Dictionary In Executor for the taskid : 2776118908102_0 Is : 31
INFO  17-07 03:10:36,236 - [Executor task launch worker-0][partitionID:nest9;queryID:2776118908102_0] Time taken to processed 1 block of output record size: 4 for the taskid : 2776118908102_0 Is : 266
Aggregation Query
INFO  17-07 03:11:57,188 - [Executor task launch worker-0][partitionID:nest9;queryID:2856578524673_0] Time taken to load the …
> [CARBONDATA-68] Log Executor Query statistics

- core/src/main/java/org/carbondata/core/cache/dictionary/ColumnDictionaryInfo.java
- core/src/main/java/org/carbondata/query/expression/conditional/EqualToExpression.java
- core/src/main/java/org/carbondata/query/expression/conditional/NotEqualsExpression.java
- core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/DictionaryColumnVisitor.java
- core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/NoDictionaryTypeVisitor.java
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonOperators.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/HighCardinalityDataTypesTestCase.scala
if the user was applying filte to list down non null members. When user applies Not Equals filter in any non null members the system shall not display null members in report as per Hive compatibility.
> [CARBONDATA-76][Bug] Null members should not display in NotEquals Filter

- integration/spark/src/main/java/org/carbondata/spark/load/DeleteLoadFolders.java
removing the segment folder after the clean up.
If a segment is deleted using the delete segment by ID DDl , then the contents inside the segment folder is getting deleted by the folder will remain in the store .
The complete folder itself can be deleted.
> [CARBONDATA-77]removing the segment folder after the clean up.

- core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
- core/src/main/java/org/carbondata/query/aggregator/impl/CountAggregator.java
- core/src/main/java/org/carbondata/query/aggregator/impl/CountStarAggregator.java
- core/src/main/java/org/carbondata/query/aggregator/util/MeasureAggregatorFactory.java
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonOperators.scala
- integration/spark/src/test/resources/datanullmeasurecol.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/CountStarTestCase.scala
CARBONDATA-17 - select count(*) from table where column_x = 'value' is not returning the correct count if the first measure is having all values null.
> CARBONDATA-17 - select count(*) from table where column_x = 'value' is not returning the correct count

- integration/spark/src/test/resources/datadelimiter.csv
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithHiveSyntax.scala
- processing/src/main/java/org/carbondata/processing/csvload/GraphExecutionUtil.java
load data when delimiter is '|' and data with header
catch exception:
```
ERROR 22-07 02:49:14,460 - [Executor task launch worker-1][partitionID:default_carbontable1_d0526816-36cd-4b1c-8547-723601e8a1d2] CSV File provided is not proper. Column names in schema and csv header are not same. CSVFile Name : datadelimiter.csv
ERROR 22-07 02:49:14,464 - [Executor task launch worker-1][partitionID:default_carbontable1_d0526816-36cd-4b1c-8547-723601e8a1d2] 
org.carbondata.processing.etl.DataLoadingException: CSV File provided is not proper. Column names in schema and csv header are not same. CSVFile Name : datadelimiter.csv
at org.carbondata.processing.csvload.DataGraphExecuter.validateCSV(DataGraphExecuter.java:139)
at org.carbondata.processing.csvload.DataGraphExecuter.validateCSVFiles(DataGraphE …
```
> [CARBONDATA-94] fixed load data when delimiter is '|' and data with header

- core/src/main/java/org/carbondata/core/locks/CarbonLockFactory.java
- integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
make the lock type as zookeeper if zookeeper URL is present in the spark conf.
if spark.deploy.zookeeper.url property is set in spark-default.conf then need to take the zookeeper locking.
> [CARBONDATA-96] Make zookeeper lock as default if zookeeper url is configured.

- examples/src/main/scala/org/carbondata/examples/ComplexTypeExample.scala
We must to add `STORED BY 'org.apache.carbondata.format' `into create statement, 
otherwise, ComplexTypeExample is an example for hive instead of for carbon
It must be merged after PR #440 ,and it also can verify whether PR #440 is proper.
> Complex type example should use carbon store format

- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonGlobalDictionaryRDD.scala
- integration/spark/src/test/scala/org/carbondata/spark/util/GlobalDictionaryUtilConcurrentTestCase.scala
In case of concurrent data loading,pre calculation of existence of dictionary file will not have proper result.
> [CARBONDATA-105]Correct precalculation of dictionary file existence

- core/src/main/java/org/carbondata/query/carbon/executor/util/QueryUtil.java
For complex type filter queries if query contains filter expres…sion rather than BinaryExpression the system was not able to get the dimensions which are involved
Also changed the logic for getting dimensions in complex type filter expressions while executing query.
Related to PR #854 With  JIRA issue 99
> [CARBONDATA-99][Bug] For complex type filter queries issue, like and not like are failing

- core/src/main/java/org/carbondata/query/filters/FilterExpressionProcessor.java
The log level has been changed to debug since its been repeatedly getting logged for each block, so if any detail level analysis is required
The developer can verify the debug level log to know how much time is taken to generate start and end key.
Also as part of log start and end key for the block will be logged.
> [CARBONDATA-115][Issue] Log level updation for better maintainability of logs

- integration/spark/src/main/scala/org/carbondata/spark/agg/CarbonAggregates.scala
- integration/spark/src/main/scala/org/carbondata/spark/util/CarbonScalaUtil.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/bigdecimal/TestBigDecimal.scala
CARBONDATA-113 url：
`https://issues.apache.org/jira/browse/CARBONDATA-113?filter=-1`
analysis:
after debuged , and found that:
1. when using decimal(27,10) (percision < 28)
logical plan keep the same with physical plan
// spark plan 
`CarbonAggregate false, [CheckOverflow((promote_precision(`cast`(SUMCarbonFinal(PartialSum#16) `as` decimal(38,10))) + 10.0000000000), DecimalType(38,10)) AS _c0#14]`
2. when using decimal(30,10)
logical plan to physical plan: the "cast ... as decimal()" has been Cut off
// spark plan 
`CarbonAggregate false, [CheckOverflow((promote_precision(SUMCarbonFinal(PartialSum#16)) + 10.0000000000), DecimalType(38,10)) AS _c0#14]`
3. for SUM + N Aggregation，the spark will cast the sum of decimal to another decimaltype
`decimal(m, n) => decimal(m+11, n)`
once the …
> [CARBONDATA-113] handle quering sum(decimal(30,10))+10

- conf/carbon.properties.template
- core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
- integration/spark/src/main/scala/org/carbondata/spark/util/CarbonScalaUtil.scala
jira url: https://issues.apache.org/jira/browse/CARBONDATA-130
when  we configurate "carbon.kettle.home" as a wrong path in carbon.properties
this adapter can help to find proper kettle home.
the function details as the following:
if "carbon.kettle.home" path is not exists, and run carbon in local mode,
According to the clues: `this class -> carbon jar path ->carbonlib -> kettle home path`
then we can get the proper kettle home
> [CARBONDATA-130]Adapt kettle home when  "carbon.kettle.home" configuration is wrong

- integration/spark/src/main/scala/org/carbondata/spark/rdd/Compactor.scala
if any thing fails in rdd and compaction is failed then throwing exception so that it will not continuously retry
> [CARBONDATA-111]not retrying compaction continuosly if compaction is failed.

- integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/MajorCompactionStopsAfterCompaction.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/joinquery/EquiJoinTestCase.scala
- processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerColumnar.java
in case of decimal measure we will get spark Decimal data type.
but in writer it expects byte array. so converting decimal to byte array.
adding test cases for same.
and correcting equijoin test case.
> [CARBONDATA-127] Decimal datatype result in cast exception in compaction

- core/src/main/java/org/carbondata/query/carbon/executor/internal/impl/InternalDetailQueryExecutor.java
- core/src/main/java/org/carbondata/query/carbon/result/iterator/AbstractDetailQueryResultIterator.java
Problem: During compaction we are calling query execution, for compaction we are doing merge sort for merge sort all the bucket must be sorted in so as we are calling query execution we can only execute one blocklet at a time, currently we are executing multiple blocklet of difference blocks. Because of this bucket records are not sorted.
Solution:Need to execute one blocklet a time during compaction
> [CARBONDATA-136]Fixed Query data mismatch issue after compaction

- integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala
Problem:In case of detail query with limit it total query execution time in statistics is printing negative values as wrong method is getting called
Solution:Need to call correct method
> [CARBONDATA-137]Fixed detail limit query statistics issue

- core/src/main/java/org/carbondata/core/datastorage/store/impl/DFSFileHolderImpl.java
- core/src/main/java/org/carbondata/core/datastorage/store/impl/FileFactory.java
Problem:When opening a input stream we are creating client every time and each time it is taking around 400 ms, In case of detail query we are opening for each blocklet and it is impacting the query performance
Solution:As query execution is a reading operation we can open only one client 
Impact Area:Query execution and compaction
> [CARBONDATA-135]Fixed multiple hdfs client creation issue

- processing/src/main/java/org/carbondata/processing/csvreaderstep/UnivocityCsvParser.java
Problem:Last Block stream was not getting closed when reading the csv file in data load.
Fix:Closing the stream when all the records are processed.
Impact Area: Data Loading
> [CARBONDATA-126]Stream not getting close for last block in data loading

- core/src/main/java/org/carbondata/query/aggregator/impl/AvgBigDecimalAggregator.java
- integration/spark/src/main/scala/org/carbondata/spark/agg/CarbonAggregates.scala
- integration/spark/src/test/scala/org/carbondata/spark/testsuite/bigdecimal/TestBigDecimal.scala
when we do avg aggregation for decimal type:
hive wiil update the precision of the avg result. 
e.g: Avg(`decimal(30,10)`), the result will be cast to `decimal(34, 14) `
so, carbon should keep the sync with hive, also need to improve the precision
the details that copyed from spark source code:
```
case class Average(child: Expression) extends UnaryExpression with PartialAggregate1 {
override def prettyName: String = "avg"
override def nullable: Boolean = true
override def dataType: DataType = child.dataType match {
case DecimalType.Fixed(precision, scale) =>
// Add 4 digits after decimal point, like Hive
DecimalType.bounded(precision + 4, scale + 4)
case _ =>
DoubleType
}
....
```
> [CARBONDATA-138] Avg aggregation for decimal type keeping sync with hive

- core/src/main/java/org/carbondata/core/reader/sortindex/CarbonDictionarySortIndexReaderImpl.java
- core/src/test/java/org/carbondata/core/reader/sortindex/CarbonDictionarySortIndexReaderImplTest.java
- core/src/test/java/org/carbondata/core/writer/sortindex/CarbonDictionarySortIndexWriterImplTest.java
Earlier we used to check size of dictionary and then create sortIndex file,to read, by appending size of dictionary e.g columid_offset.sortindex
During sort index reading phase, read offset from dictionary chunk meta and then get respective file.
> [CARBONDATA-139]Inconsistency during sortindex file reading
