HuaweiBigData/carbondata

processing/src/main/java/org/carbondata/processing/graphgenerator/GraphGenerator.java
processing/src/main/java/org/carbondata/processing/mdkeygen/MDKeyGenStep.java
processing/src/main/java/org/carbondata/processing/mdkeygen/MDKeyGenStepMeta.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdata/FileMergerParameters.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdata/IntermediateFileMerger.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdata/RowComparator.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdata/SortDataRows.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdata/SortTempFileChunkHolder.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdatastep/SortKeyStep.java
processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerColumnar.java
processing/src/main/java/org/carbondata/processing/store/SingleThreadFinalSortFilesMerger.java
processing/src/main/java/org/carbondata/processing/util/RemoveDictionaryUtil.java

Fixed final Merge sort with no dictionary column issue
Fixed parallel data writing issue

[Bug]Fixed Data loading issue

---

core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
integration/spark/src/main/scala/org/carbondata/integration/spark/rdd/CarbonDataRDDFactory.scala

force no partitioning during data load

[BUG]force no partitioning during data load

---

integration/spark/src/main/java/org/carbondata/integration/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/scala/org/apache/spark/sql/CarbonOperators.scala
integration/spark/src/main/scala/org/carbondata/integration/spark/rdd/CarbonQueryRDD.scala

1) Fixed block distribution when blocks are not uniformly replicated in cluster.
2) limit push down for detail query

[Bug] fixed blocks distribution problem, limit push down

---

integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonStrategies.scala
integration/spark/src/test/scala/org/carbondata/integration/spark/testsuite/deleteTable/TestDeleteTableNewDDL.scala

supporting the Drop table DDL syntax.
syntax is : DROP TABLE [IF EXISTS] db_name.table_name.

Drop table DDL support.

---

core/src/main/java/org/carbondata/query/carbon/aggregator/dimension/impl/FixedLengthDimensionAggregator.java
core/src/main/java/org/carbondata/query/carbon/executor/util/QueryUtil.java

Fixed non number data type dimension column aggregation issue
@TODO need to handle for other type of dimension column , variable length, column group and complex type

Fixed length dimension aggregation issue for non number data type

---

core/src/main/java/org/carbondata/core/carbon/metadata/converter/ThriftWrapperSchemaConverterImpl.java
core/src/main/java/org/carbondata/core/carbon/metadata/schema/table/column/CarbonColumn.java
core/src/main/java/org/carbondata/core/carbon/metadata/schema/table/column/ColumnSchema.java
core/src/main/java/org/carbondata/query/util/DataFileFooterConverter.java
format/src/main/thrift/schema.thrift

Cleaned Thrift files to remove unused struts and removed corresponding references from code.

Cleaned Thrift Files

---

README.md

Update README for refining some description

Update README for refining some description

---

integration/spark/src/main/scala/org/apache/spark/rdd/DummyLoadRDD.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonContext.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonOperators.scala
integration/spark/src/main/scala/org/apache/spark/sql/SparkUnknownCarbonAggregator.scala
integration/spark/src/main/scala/org/apache/spark/sql/SparkUnknownExpression.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonStrategies.scala
integration/spark/src/main/scala/org/carbondata/spark/agg/CarbonAggregates.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataPartitionRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDeleteLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonGlobalDictionaryRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/thriftserver/CarbonThriftServer.scala
integration/spark/src/main/scala/org/carbondata/spark/util/GlobalDictionaryUtil.scala
integration/spark/src/main/scala/org/carbondata/spark/util/QueryPlanUtil.scala

unify scala style don't use ';' to wrap

Unify scala style don't use ';' to wrap

---

integration/spark/src/test/resources/datawithnullmsrs.csv
integration/spark/src/test/scala/org/carbondata/integration/spark/testsuite/dataload/TestLoadDataWithNullMeasures.scala
processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerColumnar.java

fixed issue #328 
1 change calculateMaxMinUnique method name to calculateMaxMin 
2 null value don't need to call calculateMaxMin. fixed the load exception.
what's more, null measure value was stored as 0 , maybe null value should be stored as unique value.

[Issue-328]  Data load failing when the measure data is null

---

core/src/main/java/org/carbondata/core/carbon/metadata/converter/ThriftWrapperSchemaConverterImpl.java
core/src/main/java/org/carbondata/core/keygenerator/directdictionary/timestamp/TimeStampDirectDictionaryGenerator.java
core/src/main/java/org/carbondata/core/util/CarbonMetadataUtil.java
core/src/main/java/org/carbondata/query/carbon/executor/impl/QueryResultPreparator.java
core/src/main/java/org/carbondata/query/carbon/executor/util/QueryUtil.java
core/src/main/java/org/carbondata/query/expression/ExpressionResult.java
core/src/main/java/org/carbondata/query/util/DataFileFooterConverter.java
integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeDirectDictionary_FT.scala
processing/src/test/java/org/carbondata/core/keygenerator/directdictionary/timestamp/TimeStampDirectDictionaryGenerator_UT.java

1. [Issue-359] Direct Dictionary Query Flow handling as per the latest impl
2. Corrected the UT failure 
3. [Issue-374] Direct dictionary dataload failure with lenient date parsing

[Issue-359] Direct Dictionary Query Flow handling as per the latest impl & [Issue-374] Direct dictionary dataload failure with lenient date parsing

---

core/src/main/java/org/carbondata/core/keygenerator/directdictionary/DirectDictionaryKeyGeneratorFactory.java
core/src/main/java/org/carbondata/query/expression/ExpressionResult.java
core/src/main/java/org/carbondata/query/filter/executer/ExcludeFilterExecuterImpl.java
core/src/main/java/org/carbondata/query/filter/executer/IncludeFilterExecuterImpl.java
core/src/main/java/org/carbondata/query/filter/executer/RestructureFilterExecuterImpl.java
core/src/main/java/org/carbondata/query/filter/executer/RowLevelFilterExecuterImpl.java
core/src/main/java/org/carbondata/query/filter/resolver/ConditionalFilterResolverImpl.java
core/src/main/java/org/carbondata/query/filter/resolver/FilterResolverIntf.java
core/src/main/java/org/carbondata/query/filter/resolver/LogicalFilterResolverImpl.java
core/src/main/java/org/carbondata/query/filter/resolver/RestructureFilterResolverImpl.java
core/src/main/java/org/carbondata/query/filter/resolver/RowLevelFilterResolverImpl.java
core/src/main/java/org/carbondata/query/filter/resolver/metadata/FilterResolverMetadata.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/DimColumnResolvedFilterInfo.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/MeasureColumnResolvedFilterInfo.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitable/ResolvedFilterInfoVisitable.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/CustomTypeDictionaryVisitor.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/DictionaryColumnVisitor.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/FilterInfoTypeVisitorFactory.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/NoDictionaryTypeVisitor.java
core/src/main/java/org/carbondata/query/filter/resolver/resolverinfo/visitor/ResolvedFilterInfoVisitorIntf.java
core/src/main/java/org/carbondata/query/filters/FilterExpressionProcessor.java
core/src/main/java/org/carbondata/query/filters/measurefilter/util/FilterUtil.java
integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeDirectDictionary_FT.scala
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java

The below file changes is basically done for supporting direct query filter support, since the
filter value resolving mechanism is increasing the code has been re factored also for accommodating such extensions

[Issue #359]  Direct Surrogate Support

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithMalformedCarbonCommandException.scala

1. Validating load DDL with supported options 
2. Identifying duplicate options in load DDL

Validating options in load DDL

---

core/src/main/java/org/carbondata/core/util/ByteUtil.java

Please have a look at PR https://github.com/HuaweiBigData/carbondata/pull/523

Fixed error " java.lang.IllegalArgumentException: Comparison method violates its general contract! "  when nodictionary column is present.

---

integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java

Fixed #486 
currently segment merge is not supported as per new store format
disabling the segment merge feature

[Issue-486] Segment merge causing the IOException

---

processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java

Fixed data load performance issue. 
1) for each cell value we were comparing no dictionary columns with all the columns to check whether column is dictionary column or not
2) Avoid no dictionary byte array copy.now directly wrapping to byte buffer

Fixed performance issue in data load

---

integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala

Renamed schema to database and cube to table

[Issue- 591] log message correction

---

integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataretention/DataRetentionTestCase.scala

1. Delete segment without segment id should throw exception
2. using segment load time from tablestatus file instead of using thread sleep

[issue-593] Fixed delete load by id command issue

---

core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
integration/spark/src/main/java/org/carbondata/spark/load/DeleteLoadFolders.java
integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
integration/spark/src/main/java/org/carbondata/spark/util/LoadMetadataUtil.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
processing/src/main/java/org/carbondata/lcm/status/SegmentStatusManager.java

// added the compacted segment info in to the status file.

[issue-599] changes for the merge clean up.

---

core/src/main/java/org/carbondata/query/carbon/model/CarbonQueryPlan.java

Fixed multiple aggregation on same dimension column issue in query plan we were adding list for each aggregation type

[Bug]Fixed multiple aggregation on same dimesion column issue

---

core/src/main/java/org/carbondata/core/carbon/metadata/converter/SchemaConverter.java
core/src/main/java/org/carbondata/core/carbon/metadata/converter/ThriftWrapperSchemaConverterImpl.java
core/src/main/java/org/carbondata/core/carbon/metadata/schema/table/CarbonTable.java
core/src/main/java/org/carbondata/core/carbon/metadata/schema/table/TableInfo.java
hadoop/src/main/java/org/carbondata/hadoop/CarbonInputFormat.java
hadoop/src/main/java/org/carbondata/hadoop/util/SchemaReader.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/RowResultMerger.java
integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoadModel.java
integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
integration/spark/src/main/java/org/carbondata/spark/util/LoadMetadataUtil.java
integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceRelation.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/util/GlobalDictionaryUtil.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataretention/DataRetentionTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/util/GlobalDictionaryUtilTestCase.scala

Merged Ashok and My changes from the version

Store location changes

---

core/src/main/java/org/carbondata/core/carbon/datastore/block/TableBlockInfo.java

// corrected the segment id taken.

sorting will be wrong for table blocks.

---

core/src/main/java/org/carbondata/core/carbon/datastore/block/TableBlockInfo.java

// segment id is changed from int to string.
// changed != to equalignorecase.

tableblockinfo sorting was wrong.

---

core/src/main/java/org/carbondata/core/util/CarbonUtil.java
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala

[Issue-564]  clean the failed log record after drop the failed loaded table

---

core/src/main/java/org/carbondata/core/metadata/BlockletInfoColumnar.java
core/src/main/java/org/carbondata/core/util/CarbonMetadataUtil.java
core/src/main/java/org/carbondata/query/aggregator/impl/AbstractMeasureAggregatorDummy.java
core/src/main/java/org/carbondata/query/aggregator/impl/AvgBigDecimalAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/DummyBigDecimalAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/DummyDoubleAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/DummyLongAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/MaxAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/MaxBigDecimalAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/MaxLongAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/MinAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/MinBigDecimalAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/MinLongAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/SumBigDecimalAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/SumDistinctBigDecimalAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/SumDistinctDoubleAggregator.java
core/src/main/java/org/carbondata/query/aggregator/impl/SumDistinctLongAggregator.java
core/src/main/java/org/carbondata/query/carbon/result/preparator/impl/QueryResultPreparatorImpl.java
core/src/main/java/org/carbondata/query/carbon/result/preparator/impl/RawQueryResultPreparatorImpl.java
core/src/test/java/org/carbondata/core/writer/CarbonFooterWriterTest.java
integration/spark/src/main/scala/org/carbondata/spark/agg/CarbonAggregates.scala
integration/spark/src/test/resources/nullmeasurevalue.csv
integration/spark/src/test/scala/org/carbondata/spark/testsuite/measurenullvalue/NullMeasureValueTestCaseAggregate.scala
processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerColumnar.java
processing/src/main/java/org/carbondata/processing/store/writer/AbstractFactDataWriter.java
processing/src/main/java/org/carbondata/processing/store/writer/CarbonFactDataWriterImplForIntIndexAndAggBlock.java
processing/src/main/java/org/carbondata/processing/store/writer/NodeHolder.java

Fixed Null Measure Value issue , it was showing unique value need to show null in case of detail query
in case of aggregate query need to show based on aggregator
sum , avg, max, min, sum distinct will show null
for count and distinct count 0

[Bug]Null measure value issue Data mismatch

---

core/src/main/java/org/carbondata/query/carbon/aggregator/dimension/impl/VariableLengthDimensionAggregator.java
integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/HighCardinalityDataTypesTestCase.scala

fixed aggregate function like avg and sum on no dictionary column,

Fixed Aggregate Function No Dictionary Column Issue

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonStrategies.scala
integration/spark/src/test/scala/org/carbondata/integration/spark/testsuite/complexType/TestCreateTableWithDouble.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/createtable/TestCreateTableSyntax.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithHiveSyntax.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataretention/DataRetentionTestCase.scala

[Issue-587] carbon table name should be case insensitive

---

integration/spark/src/test/resources/InvalidCsvFormatdata.csv
processing/src/main/java/org/carbondata/processing/csvreaderstep/BlockDataHandler.java
processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInput.java
processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInputMeta.java
processing/src/main/java/org/carbondata/processing/graphgenerator/GraphGenerator.java
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
processing/src/main/java/org/carbondata/processing/util/CarbonDataProcessorUtil.java

[Issue - 626] csv file having some rows not in proper format is not treating them to the bad records.

---

core/src/main/java/org/carbondata/core/carbon/metadata/CarbonMetadata.java
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionNoDictionaryTest.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataretention/DataRetentionTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/deleteTable/TestDeleteTableNewDDL.scala

Refer : #660 
Show segments query should not fail, if table name is case insensitive

[Issue-660] Show segments query should not fail, if table name is case insensitive

---

core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
hadoop/src/test/java/org/carbondata/hadoop/ft/CarbonInputMapperTest.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/CarbonCompactionExecutor.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/CarbonCompactionUtil.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/CompactionCallable.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/RowResultMerger.java
integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
integration/spark/src/main/scala/org/apache/spark/sql/CarbonCatalystOperators.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/Compactor.scala
processing/src/main/java/org/carbondata/processing/graphgenerator/GraphGenerator.java
processing/src/main/java/org/carbondata/processing/mdkeygen/MDKeyGenStep.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdata/SortDataRows.java
processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerColumnar.java
processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerModel.java
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/FileStoreSurrogateKeyGenForCSV.java
processing/src/main/java/org/carbondata/processing/util/CarbonDataProcessorUtil.java

Handling of the locking mechanism for compaction using wrapper thread.
improving the logs for compaction.

Bug fix in the minor compaction segment size identification.

---

integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java

date should be checked first and then the size at last.

[Bug] Compaction: date should be checked first and then the size at last.

---

integration-testcases/pom.xml

Sparkcsv jar version

---

integration/spark/src/test/resources/InvalidCsvFormatdata.csv
processing/src/main/java/org/carbondata/processing/csvreaderstep/BlockDataHandler.java
processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInput.java
processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInputMeta.java
processing/src/main/java/org/carbondata/processing/graphgenerator/GraphGenerator.java
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
processing/src/main/java/org/carbondata/processing/util/CarbonDataProcessorUtil.java

Reverts HuaweiBigData/carbondata#627
Reverted as fix is incomplete and processing wrong records as bad records

Revert "[Issue - 626] csv file having some rows not in proper format is not treating them to the bad records."

---

core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
core/src/main/java/org/carbondata/core/locks/CarbonLockFactory.java
core/src/main/java/org/carbondata/core/locks/ZooKeeperLocking.java
core/src/test/java/org/carbondata/core/locks/ZooKeeperLockingTest.java

zookeeper path should contain schema name and table name also.

[BUG] Zookeeper lock changes to allow exclusive locks for different tables

---

core/src/main/java/org/carbondata/core/keygenerator/directdictionary/timestamp/TimeStampDirectDictionaryGenerator.java
core/src/main/java/org/carbondata/query/carbon/aggregator/dimension/impl/DirectDictionaryDimensionAggregator.java
core/src/main/java/org/carbondata/query/filter/resolver/ConditionalFilterResolverImpl.java
integration/spark/src/test/resources/datasamplenull.csv
integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeNullDataTest.scala

[Issue - 685] Support null or empty value for timestamp column

---

examples/src/main/scala/org/carbondata/examples/CarbonExample.scala

[Bug] Fix  TimeStamp convert bug in CarbonExample

---

examples/src/main/scala/org/carbondata/examples/GenerateDictionaryExample.scala

[issue-701] fixed GenerateDictionaryExample

---

integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala

Corrected audit log messages for clean, load queries

Corrected audit log messages for clean, load queries

---

core/src/main/java/org/carbondata/core/carbon/datastore/block/TableBlockInfo.java

sorting logic of the table blocks was considering task no as string which is wrong. Need to convert it to int.

[BUG] Sort is not correct for Table blocks.

---

core/src/main/java/org/carbondata/core/carbon/metadata/schema/table/CarbonTable.java
core/src/main/java/org/carbondata/core/carbon/path/CarbonTablePath.java
integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala

link issue #705 
this pr to fix data cleanup ,using new file structure  to replace old file structure which is no use.

[issue-705]Fix data cleanup before data load and data load failure

---

integration-testcases/src/test/scala/org/carbondata/spark/testsuite/allqueries/AllDataTypesTestCase4.scala
integration-testcases/src/test/scala/org/carbondata/spark/testsuite/allqueries/AllDataTypesTestCase6.scala

Corrected test cases and removed duplicate test cases

[issue - CARBONDATA-8] Test case correction

---

core/src/main/java/org/carbondata/core/carbon/datastore/block/SegmentProperties.java
core/src/main/java/org/carbondata/core/carbon/datastore/chunk/impl/ColumnGroupDimensionDataChunk.java
core/src/main/java/org/carbondata/core/util/CarbonMetadataUtil.java
core/src/main/java/org/carbondata/core/util/CarbonUtil.java
core/src/main/java/org/carbondata/core/vo/ColumnGroupModel.java
core/src/main/java/org/carbondata/query/carbon/executor/infos/KeyStructureInfo.java
core/src/main/java/org/carbondata/query/carbon/executor/util/QueryUtil.java
core/src/main/java/org/carbondata/query/filter/executer/ColGroupFilterExecuterImpl.java
core/src/test/java/org/carbondata/core/writer/CarbonFooterWriterTest.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/RowResultMerger.java
integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/ColumnGroupDataTypesTestCase.scala
processing/src/main/java/org/carbondata/processing/mdkeygen/MDKeyGenStep.java
processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerColumnar.java
processing/src/main/java/org/carbondata/processing/store/CarbonFactDataHandlerModel.java
processing/src/main/java/org/carbondata/processing/store/colgroup/ColGroupDataHolder.java
processing/src/main/java/org/carbondata/processing/store/colgroup/ColGroupMinMax.java
processing/src/main/java/org/carbondata/processing/store/writer/AbstractFactDataWriter.java
processing/src/main/java/org/carbondata/processing/store/writer/CarbonFactDataWriterImplForIntIndexAndAggBlock.java
processing/src/test/java/org/carbondata/processing/store/colgroup/ColGroupMinMaxTest.java

1.Corrected Encoding of chunk while dataloading 
2. Fixed min max issue occured due to one to one one mapping distrubance.
3. Fixed Query execution issue

[Issue 728]Column group with Dicitonary Exclude

---

core/src/main/java/org/carbondata/core/load/LoadMetadataDetails.java
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataretention/DataRetentionTestCase.scala
processing/src/main/java/org/carbondata/lcm/status/SegmentStatusManager.java

Added Validation for delete segments query, load start time parameter

Added Validation for delete segments query, load start time parameter

---

integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala

Fixed https://issues.apache.org/jira/browse/CARBONDATA-15

[issue-CARBONDATA-15] filter query throwing error if the query applied over a table having no data.

---

core/src/main/java/org/carbondata/core/carbon/datastore/BlockIndexStore.java

When number of block per task is more in that case it was getting loaded one by one and it was slow, now added thread to load the btree , if blocks are already loaded then it will not load ,if it is not loaded it will launch a thread task to load the btree. thread pool size is number of core given assigned for query ... as this is a part of query execution. 
Test cases are already present refer BlockIndexStoreTest.java

Btree loading performance improvement

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionCardinalityBoundryTest.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionLockTest.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionTest.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/HighCardinalityDataTypesTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/NullMeasureValueTestCaseFilter.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/measurenullvalue/NullMeasureValueTestCaseAggregate.scala

Removed all cube related queries

Removed all cube related queries

---

integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
processing/src/main/java/org/carbondata/lcm/status/SegmentStatusManager.java

Handling failing scenarios & providing proper logs for delete queries

Handling failing scenarios & providing proper logs for delete queries

---

common/pom.xml
common/src/main/java/org/carbondata/common/logging/impl/StandardLogService.java
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala

Added use name, thread id, database name and table name to audit log.

[Bug] add more info to audit log

---

core/src/main/java/org/carbondata/core/carbon/datastore/block/Distributable.java
core/src/main/java/org/carbondata/core/carbon/datastore/block/TableBlockInfo.java
core/src/main/java/org/carbondata/core/carbon/datastore/block/TableTaskInfo.java
core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
core/src/main/java/org/carbondata/query/carbon/executor/impl/DetailQueryExecutor.java
core/src/main/java/org/carbondata/query/carbon/executor/impl/DetailRawRecordQueryExcecutor.java
core/src/main/java/org/carbondata/query/carbon/executor/internal/impl/InternalDetailQueryExecutor.java
core/src/main/java/org/carbondata/query/carbon/model/QueryModel.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/CarbonCompactionExecutor.java
integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/java/org/carbondata/spark/merger/NodeBlockRelation.java
integration/spark/src/main/java/org/carbondata/spark/merger/NodeMultiBlockRelation.java
integration/spark/src/main/scala/org/apache/spark/sql/CarbonContext.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceHadoopRelation.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/DistributionUtil.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/Compactor.scala

1. made the limit of 120000 in memory size in case of compaction.
2. reducing the number of tasks launched in case of compaction.

[Issue-578] Improving the compaction performance.

---

core/src/main/java/org/carbondata/query/util/DataFileFooterConverter.java

index file was not getting closed.fixed the same

[bug]index file closing issue

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonContext.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/Compactor.scala

for dynamic executor allocation, taking the max executors parameter and requesting the required executors.

[Bug] Handling the dynamic executor allocation during compaction.

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonOperators.scala

Fixed: https://issues.apache.org/jira/browse/CARBONDATA-27

CARBONDATA-27 - Fixed filter expression to_date( productdate ) = '2012-12-12'

---

integration/spark/src/main/scala/org/carbondata/spark/util/CommonUtil.scala

if any invalid column is given in the column group then create should fail with error message.

[BUG] Invalid column name validation in column groups.

---

core/src/main/java/org/carbondata/query/carbon/executor/util/QueryUtil.java
integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/ColumnGroupDataTypesTestCase.scala

This change fixed Count query on column group.

[Bug]Column group count query

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/test/resources/complexTypeDecimal.csv
integration/spark/src/test/resources/complexTypeDecimalNested.csv
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithHiveSyntax.scala

Decimal type was failing in the complex type. 
Parsing of the decimal data type was wrong , corrected the same.

[BUG] Complex type decimal support

---

core/src/main/java/org/carbondata/core/util/DataTypeUtil.java
core/src/main/java/org/carbondata/query/aggregator/util/MeasureAggregatorFactory.java
core/src/main/java/org/carbondata/query/carbon/aggregator/expression/ExpressionAggregator.java
core/src/main/java/org/carbondata/query/carbon/aggregator/impl/ListBasedResultAggregator.java
core/src/main/java/org/carbondata/query/carbon/result/preparator/impl/QueryResultPreparatorImpl.java
core/src/main/java/org/carbondata/query/filter/executer/RowLevelFilterExecuterImpl.java
integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceRelation.scala
integration/spark/src/test/scala/org/carbondata/integration/spark/testsuite/dataload/TestLoadDataWithMaxMinInteger.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/aggquery/AllDataTypesTestCaseAggregate.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/allqueries/AllDataTypesTestCaseAggregate.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/detailquery/AllDataTypesTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/filterexpr/AllDataTypesTestCaseFilter.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/hadooprelation/HadoopFSRelationTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/joinquery/AllDataTypesTestCaseJoin.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/sortexpr/AllDataTypesTestCaseSort.scala

We convert int to double while data loading or query. We need to change it to BigInt

[WIP][Bug]Handling for percentile aggregate function

---

integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/scala/org/apache/spark/sql/hive/DistributionUtil.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala

CARBONDATA-58 data loading is launched with wrong number of task

---

core/src/main/java/org/carbondata/core/writer/CarbonDictionaryWriterImpl.java
core/src/main/java/org/carbondata/core/writer/sortindex/CarbonDictionarySortIndexWriterImpl.java

1.Corrected sorted index cleanup.
2.dictionary clean up on failure.

[CARBONDATA-75] Dictionary file not getting clean on global dictionary failure

---

core/src/main/java/org/carbondata/core/carbon/path/CarbonStorePath.java
core/src/main/java/org/carbondata/core/carbon/path/CarbonTablePath.java
core/src/main/java/org/carbondata/core/locks/CarbonLockFactory.java
core/src/main/java/org/carbondata/core/locks/HdfsFileLock.java
core/src/main/java/org/carbondata/core/locks/LocalFileLock.java
core/src/main/java/org/carbondata/core/locks/ZooKeeperLocking.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonGlobalDictionaryRDD.scala

1. get dictionary lock location from CarbonTablePath
2.Change lock framework to accept locklocation

[ISSUE CARBONDATA-84]Locking framework change

---

core/src/main/java/org/carbondata/core/carbon/querystatistics/QueryStatistic.java
core/src/main/java/org/carbondata/query/carbon/result/iterator/AbstractDetailQueryResultIterator.java
core/src/main/java/org/carbondata/query/carbon/result/iterator/DetailQueryResultIterator.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala

Added detail query statistics.

[CARBONDATA-68] Added query statistic for detail query case measuring carbon executor time

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceRelation.scala

In case of decimal columns, the decimal values where getting round-off values and in case of 'IN' Filters the result was not coming because of this issue.
In create command the user can set the precision and scale of a decimal column but while querying always the default value is been taken because of which the applied filter values where getting updated resulting in wrong results.

[CARBONDATA-97][Bug] Decimal Precision and scale is not getting applied based on schema metada

---

integration-testcases/src/test/scala/org/apache/spark/sql/common/util/CsvCompare.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/main/scala/org/apache/spark/sql/SparkUnknownExpression.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/test/scala/org/apache/spark/sql/TestCarbonSqlParser.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionCardinalityBoundryTest.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/DataCompactionTest.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithHiveSyntax.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeDirectDictionaryTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeDirectDictionaryWithNoDictTestCase.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/directdictionary/TimestampDataTypeNullDataTest.scala
integration/spark/src/test/scala/org/carbondata/spark/util/GlobalDictionaryUtilTestCase.scala

1. val defines a fixed value (which cannot be modified)
2. var defines a variable (which can be modified)
fixed all(about 65) the `"var could be a val"`  scala code warnings in the whole project

fixed some scala code style

---

core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/createtable/TestCreateTableSyntax.scala

when create table without key columns, it should failure and throw exception.

[BUG]Handle create table without dimensions

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala

[CARBONDATA-103] Rename CreateCube to CreateTable to correct the audit log of create table command

---

integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala

deleting the temp files in case of success / failure of load.
deleting the ktr file along with other files.

[CARBONDATA-87]deleting the temp files in case of success / failure of load.

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/apache/spark/util/FileUtils.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataload/TestLoadDataWithNotProperInputFile.scala

[CARBONDATA-106] Added audit logs for create and load failures

---

core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
core/src/main/java/org/carbondata/core/load/LoadMetadataDetails.java
integration/spark/src/main/java/org/carbondata/integration/spark/merger/CompactionCallable.java
integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/Compactor.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/MajorCompactionIgnoreInMinorTest.scala
processing/src/main/java/org/carbondata/lcm/status/SegmentStatusManager.java

Once a segment is formed using major compaction the same segment can not be considered for minor compaction.

[CARBONDATA-116]ignore the major compacted segment for minor compaction

---

integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala

Need to catch exception in compaction  and rethrow it to spark.

[CARBONDATA-111]Need to catch exception in compaction  and rethrow it to spark.

---

integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/Compactor.scala

if compaction is running and the user deleted the segment which is selected for compaction. then need to fail the compaction.

[CARBONDATA-110] delete segment selected for compaction.

---

core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
processing/src/main/java/org/carbondata/processing/mdkeygen/MDKeyGenStep.java
processing/src/main/java/org/carbondata/processing/sortandgroupby/sortdata/SortDataRows.java
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/FileStoreSurrogateKeyGenForCSV.java
processing/src/main/java/org/carbondata/processing/util/CarbonDataProcessorUtil.java

Temp locations should get deleted after the compaction is completed in RDD.

[CARBONDATA-118] Temp location clean up in compaction

---

core/src/main/java/org/carbondata/core/load/BlockDetails.java
hadoop/src/test/java/org/carbondata/hadoop/test/util/StoreCreator.java
integration/spark/src/main/scala/org/apache/spark/util/SplitUtils.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonQueryRDD.scala

Currently as there is grouping of blocks while distribution, only first option of preferred location is given to spark. So Identify the second and third option to schedule.

[CARBONDATA-122] Block distribution give second and third preferred locaiton

---

integration/spark/src/main/java/org/carbondata/spark/merger/CarbonDataMergerUtil.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/datacompaction/MajorCompactionStopsAfterCompaction.scala

Need to identify the segments for merging each time after one compaction is done.
as the user can delete some loads in between the compaction process.

[CARBONDATA-121]Need to identify the segments for merging each time after one compaction

---

integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonGlobalDictionaryRDD.scala

Added null check before adding to carbonproperties.

[Issue CARBONDATA-129]Add null check before adding to CarbonProperties.

---

integration-testcases/src/test/scala/org/carbondata/spark/testsuite/allqueries/AllDataTypesTestCase4.scala
integration-testcases/src/test/scala/org/carbondata/spark/testsuite/allqueries/AllDataTypesTestCase6.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/dataretention/DataRetentionTestCase.scala

Deleted load/loads support & using only segment/segments in all commands

Deleted load/loads support from DDL commands

---

integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonDataLoadRDD.scala
integration/spark/src/main/scala/org/carbondata/spark/rdd/CarbonMergerRDD.scala
processing/src/main/java/org/carbondata/processing/csvreaderstep/CsvInput.java
processing/src/main/java/org/carbondata/processing/surrogatekeysgenerator/csvbased/CarbonCSVBasedSeqGenStep.java

changing store location to inside that of the container.

[CARBONDATA-134]changing store location to inside that of the container.
